import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../dashboard/index.html',import.meta.url),'utf8');
const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const DATA ='));
assert.ok(code,'A generated dashboard contract is required');
const elements=new Map();
const captures=[];
const element=id=>{if(!elements.has(id))elements.set(id,{value:'',hidden:id==='outlook'||id==='methods',innerHTML:'',textContent:'',listeners:{},addEventListener(event,fn){this.listeners[event]=fn;}});return elements.get(id);};
const context=vm.createContext({document:{getElementById:element,querySelectorAll:()=>[],createElement:()=>({click(){}})},Plotly:{react(){}},Blob,URL:{createObjectURL(blob){captures.push(blob);return 'blob:test';},revokeObjectURL(){}},setTimeout(fn){fn();}});
vm.runInContext(code,context);
element('state').value='NT';element('start-year').value='2020';element('end-year').value='2023';vm.runInContext('refresh()',context);
element('download-briefing').listeners.click();
const brief=await captures[0].text();
assert.match(brief,/# NT transport emissions briefing/);
assert.match(brief,/FY2020-21.*FY2023-24/);
assert.match(brief,/dcceew.gov.au/);
assert.match(brief,/Same-holdout seasonal-naive MAPE/);
assert.match(brief,/95% band/);
assert.match(brief,/Pipeline run: [a-f0-9]{16}/);
element('download-data').listeners.click();
const csv=await captures[1].text();
assert.equal(csv.split('\r\n').length,5,'Four selected years plus header');
assert.match(csv,/pipeline_run_id/);
assert.match(csv,/"NT","2020"/);
assert.equal(captures[1].type,'text/csv');
console.log('Dashboard Markdown/CSV exports passed: filters, units, sources, run identity, holdout baseline and coverage.');
