import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const html=fs.readFileSync(new URL('../dashboard/index.html',import.meta.url),'utf8');
const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('let DATA ='));
assert.ok(code,'The generated market dashboard is required');
const elements=new Map(),saved=new Map(),downloads=[];
let blockStorage=false;
const element=id=>{if(!elements.has(id))elements.set(id,{value:'',clientWidth:500,clientHeight:295,textContent:'',innerHTML:'',hidden:false,listeners:{},dataset:{},classList:{toggle(){}},setAttribute(){},focus(){},addEventListener(event,fn){this.listeners[event]=fn;}});return elements.get(id)};
const tabs=['review','outlook','evidence'].map(id=>{const button=element('tab-'+id);button.dataset.page=id;return button});
const periods=[90,30,365].map(days=>{const button=element('days-'+days);button.dataset.days=String(days);return button});
let printed=0;
const context=vm.createContext({document:{body:{appendChild(){}},getElementById:element,querySelectorAll:selector=>selector==='[data-page]'?tabs:selector==='[data-days]'?periods:[],createElement:()=>({click(){},remove(){}})},Plotly:{react(){}},Blob,Date,URL:{createObjectURL(blob){downloads.push(blob);return 'blob:test';},revokeObjectURL(){}},localStorage:{getItem:key=>saved.get(key)??null,setItem:(key,value)=>{if(blockStorage)throw new Error('Storage blocked');saved.set(key,value)},removeItem:key=>saved.delete(key)},location:{protocol:'file:'},window:{print(){printed++},scrollTo(){},addEventListener(){}},setTimeout(fn){return 0},clearTimeout(){}});
vm.runInContext(code,context);
assert.match(element('price-cards').innerHTML,/Sydney/);
element('state').value='NT';element('fuel').value='Petrol';element('state').listeners.change();
assert.match(element('price-cards').innerHTML,/Darwin terminal price/);
assert.match(element('scope-label').innerHTML,/national/);
element('analyst-notes').value='Demo note: verify the published observation dates <script>example</script>';
element('analyst-notes').listeners.input();
assert.match(element('briefing-document').textContent,/NT · Petrol/);
assert.match(element('briefing-document').textContent,/Demo note:/);
element('download-briefing').listeners.click();
const text=await downloads[0].text();
assert.match(text,/NT · Petrol/);
assert.match(text,/Darwin wholesale terminal price/);
assert.match(text,/National petrol MSO holdings/);
assert.match(text,/seasonal-naive baseline/);
assert.match(text,/aip.com.au/);
assert.match(text,/Demo note:/);
assert.match(text,/six-month state sales outlook/i);
element('download-data').listeners.click();
const csv=await downloads[1].text();
assert.match(csv,/'?"scope"/);
assert.match(csv,/"Darwin"/);
assert.match(csv,/"National"/);
assert.match(csv,/"NT"/);
assert.match(csv,/"upper_95"/);
element('save-checkpoint').listeners.click();
assert.match(element('checkpoint-description').textContent,/No source-file change/);
element('print-briefing').listeners.click();
assert.equal(printed,1);
assert.match(element('print-report').innerHTML,/&lt;script&gt;example&lt;\/script&gt;/);
assert.doesNotMatch(element('print-report').innerHTML,/<script>example/);
element('clear-checkpoint').listeners.click();
assert.match(element('local-review-status').textContent,/No review checkpoint/);
tabs[1].listeners.click();
assert.match(element('forecast-title').textContent,/NT petrol sales outlook/);
assert.match(element('forecast-cards').innerHTML,/6 months/);
assert.match(element('forecast-table').innerHTML,/Timing/);
blockStorage=true;
element('save-checkpoint').listeners.click();
assert.match(element('toast').textContent,/storage is unavailable/i);
assert.doesNotMatch(element('toast').textContent,/checkpoint saved/i);
console.log('Market dashboard: state/fuel selection, scoped exports, source links, notes, unchanged checkpoints, safe printing and six-month outlook passed.');
