"""
app/api.py
----------
Stage 7 of the project lifecycle: Deployment (model/API).

A small FastAPI service that:
  - exposes the trained regression model (reports/model_results/
    emissions_regression.pkl) for scoring, so it can be called by
    something other than this repo's own scripts
  - reads the analysis-ready tables from the DBMS (src/db.py), not raw
    CSVs, so this is a genuine "serve from the database" deployment
  - re-uses the same monitoring/drift report the Monitoring stage writes

Run:
    uvicorn app.api:app --reload --host 0.0.0.0 --port 8000

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs

Endpoints:
    GET  /health                      liveness check
    GET  /states                      list of states available in the DB
    GET  /metrics                     model_metrics table, as JSON
    GET  /monitoring/drift            latest drift_report.json, if it exists
    POST /predict                     score the regression model on new inputs
"""

from __future__ import annotations

import json
import pickle
import sys
from pathlib import Path
from typing import Optional

import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src import db  # noqa: E402

MODEL_PATH = REPO_ROOT / "reports" / "model_results" / "emissions_regression.pkl"
DRIFT_REPORT_PATH = REPO_ROOT / "reports" / "monitoring" / "drift_report.json"

app = FastAPI(
    title="Transport Emissions API",
    description="Serves the trained emissions regression model and the "
                 "analysis-ready tables from this project's DBMS.",
    version="1.0.0",
)

_model = None  # lazy-loaded on first /predict call


class PredictRequest(BaseModel):
    fuel_consumption_ml: float = Field(..., description="Annual fuel consumption, megalitres")
    vkt_road_million_km: float = Field(..., description="Annual road VKT, million km")
    registered_vehicles: int = Field(..., description="Registered vehicles, count")


class PredictResponse(BaseModel):
    predicted_ghg_kt_co2e: float
    caveat: str


def _get_model():
    global _model
    if _model is None:
        if not MODEL_PATH.exists():
            raise HTTPException(
                status_code=503,
                detail=f"Model file not found at {MODEL_PATH} -- run `python run_pipeline.py` first.",
            )
        with open(MODEL_PATH, "rb") as f:
            _model = pickle.load(f)
    return _model


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/states")
def states() -> list[str]:
    engine = db.get_engine()
    try:
        df = pd.read_sql("SELECT DISTINCT state FROM annual_master ORDER BY state", engine)
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"Could not read from the database ({e}) -- run `python run_pipeline.py` first.",
        )
    return df["state"].tolist()


@app.get("/metrics")
def metrics(result_group: Optional[str] = None) -> list[dict]:
    engine = db.get_engine()
    try:
        query = "SELECT * FROM model_metrics"
        params = {}
        if result_group:
            query += " WHERE result_group = :result_group"
            params["result_group"] = result_group
        df = pd.read_sql(query, engine, params=params)
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Could not read model_metrics: {e}")
    return df.to_dict(orient="records")


@app.get("/monitoring/drift")
def monitoring_drift() -> dict:
    if not DRIFT_REPORT_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="No drift report yet -- run `python monitoring/monitor.py` first.",
        )
    return json.loads(DRIFT_REPORT_PATH.read_text())


@app.post("/predict", response_model=PredictResponse)
def predict(payload: PredictRequest) -> PredictResponse:
    model = _get_model()
    X = [[payload.fuel_consumption_ml, payload.vkt_road_million_km, payload.registered_vehicles]]
    pred = float(model.predict(X)[0])
    return PredictResponse(
        predicted_ghg_kt_co2e=round(pred, 2),
        caveat=(
            "Trained on real Australian data where state emissions are "
            "*constructed from* fuel sales via published NGA factors -- "
            "expect a near-tautological fit, not a novel predictive signal. "
            "See README.md's real-data caveats before citing this."
        ),
    )
