[server]
address = "127.0.0.1"
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 25
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#245DA8"
backgroundColor = "#F6F9FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#162A43"
font = "sans serif"
